# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      shell: bash
      run: |
        dotnet build --no-restore --configuration Release
        7z a -tzip "Kalkulator.zip" "/home/runner/work/kalkulator-projekt-programowanie-obiektowe-i-graficzne/kalkulator-projekt-programowanie-obiektowe-i-graficzne/Kalkulator/bin/Release/*"
      
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Kalkulator.zip

                  
              
